### ISSUE TITLE
Bug: Model format error, expect a tree here. met <F0>

### ISSUE THREAD

**Issue by PhilipMay** [microsoft/LightGBM#2828]
## Environment info

- Operating System: Ubuntu 18.04.3 LTS (bionic)
- CPU/GPU model: not using GPU
- C++/Python/R version: Python 3.6
- LightGBM version or commit hash: lightgbm 2.3.1 (from pip)

## Error message

```
[LightGBM] [Fatal] Model format error, expect a tree here. met
[LightGBM] [Fatal] Model format error, expect a tree here. met
[LightGBM] [Warning] Model format error, expect a tree here. met
[LightGBM] [Fatal] Model format error, expect a tree here. met <F0>?
[LightGBM] [Warning] Model format error, expect a tree here. met <F0>?
[LightGBM] [Fatal] Model format error, expect a tree here. met
[LightGBM] [Warning] Model format error, expect a tree here. met
[LightGBM] [Fatal] Model format error, expect a tree here. met
[LightGBM] [Warning] Model format error, expect a tree here. met
[LightGBM] [Fatal] Model format error, expect a tree here. met
[LightGBM] [Warning] Model format error, expect a tree here. met
[LightGBM] [Fatal] Model format error, expect a tree here. met
[LightGBM] [Warning] Model format error, expect a tree here. met
[LightGBM] [Fatal] Model format error, expect a tree here. met
[LightGBM] [Warning] Model format error, expect a tree here. met
[LightGBM] [Fatal] Model format error, expect a tree here. met
[LightGBM] [Warning] Model format error, expect a tree here. met
[LightGBM] [Fatal] Model format error, expect a tree here. met
[LightGBM] [Warning] Model format error, expect a tree here. met
[LightGBM] [Fatal] Model format error, expect a tree here. met
[LightGBM] [Fatal] Model format error, expect a tree here. met
[LightGBM] [Warning] Model format error, expect a tree here. met
[LightGBM] [Warning] Model format error, expect a tree here. met
[LightGBM] [Fatal] Model format error, expect a tree here. met
[LightGBM] [Warning] Model format error, expect a tree here. met
[LightGBM] [Fatal] Model format error, expect a tree here. met
[LightGBM] [Fatal] Model format error, expect a tree here. met
[LightGBM] [Warning] Model format error, expect a tree here. met
[LightGBM] [Warning] Model format error, expect a tree here. met
[LightGBM] [Fatal] Model format error, expect a tree here. met <F0>?
[LightGBM] [Warning] Model format error, expect a tree here. met
[LightGBM] [Fatal] Model format error, expect a tree here. met
[LightGBM] [Fatal] Model format error, expect a tree here. met
[LightGBM] [Warning] Model format error, expect a tree here. met <F0>?
[LightGBM] [Warning] Model format error, expect a tree here. met
[LightGBM] [Warning] Model format error, expect a tree here. met
[LightGBM] [Fatal] Model format error, expect a tree here. met
[LightGBM] [Fatal] Model format error, expect a tree here. met
[LightGBM] [Warning] Model format error, expect a tree here. met
[LightGBM] [Warning] Model format error, expect a tree here. met
[LightGBM] [Fatal] Model format error, expect a tree here. met
[LightGBM] [Warning] Model format error, expect a tree here. met
[LightGBM] [Fatal] Model format error, expect a tree here. met
... and so on ...
[LightGBM] [Fatal] Model format error, expect a tree here. met
[LightGBM] [Warning] Model format error, expect a tree here. met
[LightGBM] [Fatal] Model format error, expect a tree here. met
[LightGBM] [Warning] Model format error, expect a tree here. met
[LightGBM] [Fatal] Model format error, expect a tree here. met
[LightGBM] [Warning] Model format error, expect a tree here. met
[LightGBM] [Fatal] Model format error, expect a tree here. met
[LightGBM] [Warning] Model format error, expect a tree here. met
[LightGBM] [Fatal] Model format error, expect a tree here. met
[LightGBM] [Warning] Model format error, expect a tree here. met
[LightGBM] [Fatal] Model format error, expect a tree here. met
[LightGBM] [Warning] Model format error, expect a tree here. met
[LightGBM] [Fatal] Model format error, expect a tree here. met
[LightGBM] [Warning] Model format error, expect a tree here. met
[LightGBM] [Fatal] Model format error, expect a tree here. met
[LightGBM] [Warning] Model format error, expect a tree here. met
[LightGBM] [Fatal] Model format error, expect a tree here. met
[LightGBM] [Warning] Model format error, expect a tree here. met
[LightGBM] [Fatal] Model format error, expect a tree here. met
[LightGBM] [Warning] Model format error, expect a tree here. met
terminate called without an active exception
```

## Reproducible examples

I am doing regression on this data:
```
x.shape: (169889, 7354)
y.shape: (169889,)
```

I am doing 5 fold cross val.
On fold number 4 this error happens.
It is ok with fold 1 to 3.
It happens with default hyperparameters and other hyperparameters.

**Comment by guolinke** [comment]
Do you edit model file by hand, like the replacing the new line symbol? Do you use the some version of LightGBM for loading and save?
Do you use the different model save path for different folds?

**Comment by PhilipMay** [comment]
I am not even loading and saving anything. I have a .py script.
It loads a pandas frame. Creates x and y from it. Then optuna is used for hyperopt and
I am usinig KFold to do 5 fold xvalidation. No loading, no saving, no model file, no different versions.

**Comment by guolinke** [comment]
@PhilipMay thanks for clarifying. I guess some intermedia model string is changed in python, like encoding issues. Not sure why it happens, but it seems related to the hyper-parameter searching tools. 

A reproduce example with minimal dependencies would be better.

**Comment by PhilipMay** [comment]
Ok - will se what I can find out.

**Comment by PhilipMay** [comment]
Well - I think this issue might be connected to low memory problems. Closing this again.
Thanks for the feedback though.

**Comment by PhilipMay** [comment]
@guolinke Here is a better log of the problem. Can you please have a look?

For me it seems like C++ is trying to give back the model to python, serialises it and then runs oom. Before I start the training run I have only 24.2 % of used memory (see 1st line in log). I have a total of 128 GB RAM. 

Maybe I have to limit the numeber of trees / boosting rounds. At the moment I am only using early stopping with a limit of 10000. I am getting 130 to 200 Boosting rounds before it early stops.

```
svmem(total=134864719872, available=102212935680, percent=24.2, used=31480340480, free=101417074688, active=32447553536, inactive=426053632, buffers=443588608, cached=1523716096, shared=323584, slab=309993472)
[W 2020-02-28 11:49:33,909] Setting status of trial#62 as TrialState.FAIL because of the following error: LightGBMError('std::bad_alloc')
Traceback (most recent call last):
  File "/home/phmay/miniconda3/envs/geb/lib/python3.7/site-packages/optuna/study.py", line 569, in _run_trial
    result = func(trial)
  File "04_training_01.py", line 178, in objective
    num_boost_round  = 10000,
  File "/home/phmay/miniconda3/envs/geb/lib/python3.7/site-packages/lightgbm/engine.py", line 273, in train
    booster.model_from_string(booster.model_to_string(), False).free_dataset()
  File "/home/phmay/miniconda3/envs/geb/lib/python3.7/site-packages/lightgbm/basic.py", line 2316, in model_to_string
    ptr_string_buffer))
  File "/home/phmay/miniconda3/envs/geb/lib/python3.7/site-packages/lightgbm/basic.py", line 45, in _safe_call
    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
lightgbm.basic.LightGBMError: std::bad_alloc
Traceback (most recent call last):
  File "04_training_01.py", line 231, in <module>
    study.optimize(objective)
  File "/home/phmay/miniconda3/envs/geb/lib/python3.7/site-packages/optuna/study.py", line 302, in optimize
    gc_after_trial, None)
  File "/home/phmay/miniconda3/envs/geb/lib/python3.7/site-packages/optuna/study.py", line 538, in _optimize_sequential
    self._run_trial_and_callbacks(func, catch, callbacks, gc_after_trial)
  File "/home/phmay/miniconda3/envs/geb/lib/python3.7/site-packages/optuna/study.py", line 550, in _run_trial_and_callbacks
    trial = self._run_trial(func, catch, gc_after_trial)
  File "/home/phmay/miniconda3/envs/geb/lib/python3.7/site-packages/optuna/study.py", line 569, in _run_trial
    result = func(trial)
  File "04_training_01.py", line 178, in objective
    num_boost_round  = 10000,
  File "/home/phmay/miniconda3/envs/geb/lib/python3.7/site-packages/lightgbm/engine.py", line 273, in train
    booster.model_from_string(booster.model_to_string(), False).free_dataset()
  File "/home/phmay/miniconda3/envs/geb/lib/python3.7/site-packages/lightgbm/basic.py", line 2316, in model_to_string
    ptr_string_buffer))
  File "/home/phmay/miniconda3/envs/geb/lib/python3.7/site-packages/lightgbm/basic.py", line 45, in _safe_call
    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
lightgbm.basic.LightGBMError: std::bad_alloc
```

**Comment by PhilipMay** [comment]
Reopened it.

**Comment by guolinke** [comment]
You can set keep_training_booster to avoid the serializtion. However, this may cause  more memories...

**Comment by PhilipMay** [comment]
@guolinke Yes - it fixes the problem. I am not sure if this issue should be just closed.
Maybe at least the `keep_training_booster` parameter should be documented better.

What do you think?

**Comment by guolinke** [comment]
@PhilipMay yeah, good suggestion. Thanks very much.

**Comment by aegonwolf** [comment]
same error, just loading the same script on a different laptop.
